require("dotenv").config();
const { PrismaClient } = require("@prisma/client");
const { PrismaPg } = require("@prisma/adapter-pg");
const pg = require("pg");

const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const products = [
  {
    id: "veg_potato",
    nameEn: "Potato",
    nameGu: "બટાકા",
    category: "Vegetable",
    prices: { "250g": 10, "500g": 20, "1kg": 30 },
    svgType: "potato",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&q=80",
  },
  {
    id: "veg_onion",
    nameEn: "Onion",
    nameGu: "ડુંગળી",
    category: "Vegetable",
    prices: { "250g": 15, "500g": 25, "1kg": 40 },
    svgType: "onion",
    imageUrl: "https://images.unsplash.com/photo-1508747703725-719777637510?w=300&q=80",
  },
  {
    id: "veg_locker_potato",
    nameEn: "Locker Potato",
    nameGu: "લોકર બટાકા",
    category: "Vegetable",
    prices: { "250g": 15, "500g": 25, "1kg": 45 },
    svgType: "potato",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&q=80",
  },
  {
    id: "veg_brinjal",
    nameEn: "Brinjal",
    nameGu: "રીંગણ",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 30, "1kg": 50 },
    svgType: "brinjal",
    imageUrl: "https://images.unsplash.com/photo-1613743983303-b3e89f8a2b80?w=300&q=80",
  },
  {
    id: "veg_tomatoes",
    nameEn: "Tomatoes",
    nameGu: "ટામેટા",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 40, "1kg": 80 },
    svgType: "tomato",
    imageUrl: "https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=300&q=80",
  },
  {
    id: "veg_cabbage",
    nameEn: "Cabbage",
    nameGu: "કોબીજ",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 40, "1kg": 80 },
    svgType: "cabbage",
    imageUrl: "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=300&q=80",
  },
  {
    id: "veg_cauliflower",
    nameEn: "Cauliflower",
    nameGu: "ફુલાવર",
    category: "Vegetable",
    prices: { "250g": 40, "500g": 75, "1kg": 130 },
    svgType: "cauliflower",
    imageUrl: "https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?w=300&q=80",
  },
  {
    id: "veg_bottle_gourd",
    nameEn: "Bottle Gourd",
    nameGu: "દૂધી",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 30, "1kg": 50 },
    svgType: "gourd",
    imageUrl: "https://images.unsplash.com/photo-1596887235673-50baf80e6b2b?w=300&q=80",
  },
  {
    id: "veg_luffa_gourd",
    nameEn: "Luffa Gourd",
    nameGu: "ગલકા",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 30, "1kg": 55 },
    svgType: "gourd",
  },
  {
    id: "veg_bitter_gourd",
    nameEn: "Bitter Gourd",
    nameGu: "કારેલા",
    category: "Vegetable",
    prices: { "250g": 35, "500g": 65, "1kg": 110 },
    svgType: "bittergourd",
  },
  {
    id: "veg_lady_finger",
    nameEn: "Lady Finger",
    nameGu: "ભીંડા",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 40, "1kg": 75 },
    svgType: "bean",
    imageUrl: "https://images.unsplash.com/photo-1521115713617-3e6bf0f2ff19?w=300&q=80",
  },
  {
    id: "veg_pointed_gourd",
    nameEn: "Pointed Gourd",
    nameGu: "પરવર",
    category: "Vegetable",
    prices: { "250g": 30, "500g": 60, "1kg": 100 },
    svgType: "gourd",
  },
  {
    id: "veg_peas",
    nameEn: "Peas",
    nameGu: "વટાણા",
    category: "Vegetable",
    prices: { "250g": 50, "500g": 90, "1kg": 160 },
    svgType: "peas",
    imageUrl: "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=300&q=80",
  },
  {
    id: "veg_ivy_gourd",
    nameEn: "Ivy Gourd",
    nameGu: "ટીંડોળા",
    category: "Vegetable",
    prices: { "250g": 30, "500g": 55, "1kg": 100 },
    svgType: "gourd",
  },
  {
    id: "veg_pigeon_peas",
    nameEn: "Pigeon Peas",
    nameGu: "તુવેર",
    category: "Vegetable",
    prices: { "250g": 50, "500g": 90, "1kg": 150 },
    svgType: "peas",
  },
  {
    id: "veg_cluster_beans",
    nameEn: "Cluster Beans",
    nameGu: "ગુવાર",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 45, "1kg": 85 },
    svgType: "bean",
  },
  {
    id: "veg_flat_beans",
    nameEn: "Flat Beans",
    nameGu: "વાલોર પાપડી",
    category: "Vegetable",
    prices: { "250g": 45, "500g": 80, "1kg": 150 },
    svgType: "bean",
  },
  {
    id: "veg_green_bean",
    nameEn: "Green Bean",
    nameGu: "ચોળી",
    category: "Vegetable",
    prices: { "250g": 45, "500g": 80, "1kg": 150 },
    svgType: "bean",
  },
  {
    id: "veg_carrot",
    nameEn: "Carrot",
    nameGu: "ગાજર",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 35, "1kg": 55 },
    svgType: "carrot",
    imageUrl: "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=300&q=80",
  },
  {
    id: "veg_cucumber",
    nameEn: "Cucumber",
    nameGu: "કાકડી",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 50, "1kg": 80 },
    svgType: "cucumber",
    imageUrl: "https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=300&q=80",
  },
  {
    id: "veg_beetroot",
    nameEn: "Beetroot",
    nameGu: "બીટ",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 35, "1kg": 55 },
    svgType: "beetroot",
  },
  {
    id: "veg_capsicum",
    nameEn: "Capsicum",
    nameGu: "શિમલા",
    category: "Vegetable",
    prices: { "250g": 35, "500g": 70, "1kg": 140 },
    svgType: "pepper",
  },
  {
    id: "veg_chili",
    nameEn: "Chili",
    nameGu: "મરચાં",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 45, "1kg": 85 },
    svgType: "chili",
  },
  {
    id: "veg_hot_chili",
    nameEn: "Hot Chili",
    nameGu: "તીખા મરચાં",
    category: "Vegetable",
    prices: { "250g": 35, "500g": 65, "1kg": 120 },
    svgType: "chili",
  },
  {
    id: "veg_ginger",
    nameEn: "Ginger",
    nameGu: "આદુ",
    category: "Vegetable",
    prices: { "250g": 50, "500g": 90, "1kg": 170 },
    svgType: "ginger",
    imageUrl: "https://images.unsplash.com/photo-1615485500704-8e990f9900f6?w=300&q=80",
  },
  {
    id: "veg_lemon",
    nameEn: "Lemon",
    nameGu: "લીંબુ",
    category: "Vegetable",
    prices: { "250g": 40, "500g": 85, "1kg": 150 },
    svgType: "lemon",
  },
  {
    id: "leaf_coriander",
    nameEn: "Coriander",
    nameGu: "ધાણા",
    category: "Leafy",
    prices: { "250g": 30, "500g": 55, "1kg": 100 },
    svgType: "leafy",
    imageUrl: "https://images.unsplash.com/photo-1615484477778-ca3b77940c25?w=300&q=80",
  },
  {
    id: "leaf_fenugreek",
    nameEn: "Fenugreek",
    nameGu: "મેથી",
    category: "Leafy",
    prices: { "250g": 35, "500g": 65, "1kg": 120 },
    svgType: "leafy",
    imageUrl: "https://images.unsplash.com/photo-1603048297172-7c72a7c76f1a?w=300&q=80",
  },
  {
    id: "leaf_spinach",
    nameEn: "Spinach",
    nameGu: "પાલક",
    category: "Leafy",
    prices: { "250g": 20, "500g": 35, "1kg": 60 },
    svgType: "spinach",
    imageUrl: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=300&q=80",
  },
  {
    id: "leaf_amaranth",
    nameEn: "Amaranth Leaves",
    nameGu: "તાંદળજાની ભાજી",
    category: "Leafy",
    prices: { "250g": 25, "500g": 45, "1kg": 70 },
    svgType: "leafy",
  },
  {
    id: "leaf_peppermint",
    nameEn: "Peppermint",
    nameGu: "ફુદીનો",
    category: "Leafy",
    prices: { "250g": 35, "500g": 60, "1kg": 110 },
    svgType: "leafy",
  },
  {
    id: "fv_raw_mango",
    nameEn: "Raw Mango",
    nameGu: "કાચી કેરી",
    category: "Fruit/Veg",
    prices: { "250g": 25, "500g": 45, "1kg": 80 },
    svgType: "mango",
    imageUrl: "https://images.unsplash.com/photo-1553279768-865429fa0078?w=300&q=80",
  },
  {
    id: "veg_corn",
    nameEn: "Corn",
    nameGu: "મકાઈ",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 35, "1kg": 60 },
    svgType: "corn",
    imageUrl: "https://images.unsplash.com/photo-1601593768793-bb1c8f0c8e46?w=300&q=80",
  },
  {
    id: "veg_drumstick",
    nameEn: "Drumstick",
    nameGu: "સરગવો",
    category: "Vegetable",
    prices: { "250g": 35, "500g": 60, "1kg": 110 },
    svgType: "bean",
  },
  {
    id: "leaf_spring_onion",
    nameEn: "Spring Onion",
    nameGu: "લીલી ડુંગળી",
    category: "Leafy",
    prices: { "250g": 30, "500g": 50, "1kg": 90 },
    svgType: "onion",
  },
  {
    id: "veg_elephant_yam",
    nameEn: "Elephant Yam",
    nameGu: "સૂરણ",
    category: "Vegetable",
    prices: { "250g": 30, "500g": 55, "1kg": 90 },
    svgType: "potato",
  },
  {
    id: "leaf_dill",
    nameEn: "Dill Leaves",
    nameGu: "સુવાની ભાજી",
    category: "Leafy",
    prices: { "250g": 35, "500g": 70, "1kg": 140 },
    svgType: "leafy",
  },
  {
    id: "veg_green_brinjal",
    nameEn: "Green Brinjal",
    nameGu: "લીલા રીંગણ",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 30, "1kg": 55 },
    svgType: "brinjal",
  },
  {
    id: "veg_french_beans",
    nameEn: "French Beans",
    nameGu: "ફણસી",
    category: "Vegetable",
    prices: { "250g": 40, "500g": 90, "1kg": 140 },
    svgType: "bean",
  },
  {
    id: "veg_ridge_gourd",
    nameEn: "Ridge Gourd",
    nameGu: "તુરીયા",
    category: "Vegetable",
    prices: { "250g": 40, "500g": 75, "1kg": 130 },
    svgType: "gourd",
  },
  {
    id: "veg_raw_banana",
    nameEn: "Raw Banana",
    nameGu: "કાચા કેળા",
    category: "Vegetable",
    prices: { "250g": 10, "500g": 25, "1kg": 40 },
    svgType: "banana",
  },
  {
    id: "veg_pumpkin",
    nameEn: "Pumpkin",
    nameGu: "કોળું",
    category: "Vegetable",
    prices: { "250g": 30, "500g": 55, "1kg": 90 },
    svgType: "pumpkin",
  },
  {
    id: "veg_garlic",
    nameEn: "Garlic",
    nameGu: "લસણ",
    category: "Vegetable",
    prices: { "250g": 60, "500g": 120, "1kg": 200 },
    svgType: "garlic",
  },
  {
    id: "leaf_lemongrass",
    nameEn: "Lemongrass",
    nameGu: "લીલી ચા",
    category: "Leafy",
    prices: { "250g": 25, "500g": 45, "1kg": 80 },
    svgType: "leafy",
  },
  {
    id: "leaf_colocasia",
    nameEn: "Colocasia Leaves",
    nameGu: "પતરવેલિ પાન",
    category: "Leafy",
    prices: { "250g": 35, "500g": 70, "1kg": 130 },
    svgType: "leafy",
  },
  {
    id: "spr_moth",
    nameEn: "Sprouted Moth Beans",
    nameGu: "ફણગાવેલા મઠ",
    category: "Sprouts",
    prices: { "250g": 30, "500g": 60, "1kg": 90 },
    svgType: "sprouts",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=300&q=80",
  },
  {
    id: "spr_mung",
    nameEn: "Sprouted Mung Beans",
    nameGu: "ફણગાવેલા મગ",
    category: "Sprouts",
    prices: { "250g": 30, "500g": 60, "1kg": 90 },
    svgType: "sprouts",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=300&q=80",
  },
  {
    id: "spr_chickpeas",
    nameEn: "Sprouted Chickpeas",
    nameGu: "ફણગાવેલા ચણા",
    category: "Sprouts",
    prices: { "250g": 30, "500g": 60, "1kg": 90 },
    svgType: "sprouts",
    imageUrl: "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?w=300&q=80",
  },
  {
    id: "veg_taro_root",
    nameEn: "Taro Root",
    nameGu: "અળવી",
    category: "Vegetable",
    prices: { "250g": 25, "500g": 45, "1kg": 80 },
    svgType: "potato",
  },
  {
    id: "veg_green_garlic",
    nameEn: "Green Garlic",
    nameGu: "લીલું લસણ",
    category: "Vegetable",
    prices: { "250g": 20, "500g": 35, "1kg": 60 },
    svgType: "garlic",
  },
  {
    id: "veg_mushroom",
    nameEn: "Mushroom",
    nameGu: "મશરૂમ",
    category: "Vegetable",
    prices: { "200g_packet": 65 },
    svgType: "mushroom",
    imageUrl: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=300&q=80",
  },
  {
    id: "dairy_cow_ghee",
    nameEn: "Pure Cow Ghee",
    nameGu: "શુદ્ધ ગાયનું ઘી",
    category: "Dairy",
    prices: { "1kg": 1200 },
    svgType: "ghee",
    imageUrl: "https://images.unsplash.com/photo-1631897642040-db065be6bf7d?w=300&q=80",
  },
  {
    id: "dairy_buffalo_ghee",
    nameEn: "Pure Buffalo Ghee",
    nameGu: "શુદ્ધ ભેંસનું ઘી",
    category: "Dairy",
    prices: { "1kg": 1000 },
    svgType: "ghee",
    imageUrl: "https://images.unsplash.com/photo-1631897642040-db065be6bf7d?w=300&q=80",
  },
];

const categories = [
  { id: "Vegetable", name: "Vegetables" },
  { id: "Leafy", name: "Leafy Greens" },
  { id: "Fruit/Veg", name: "Fruit/Veg" },
  { id: "Sprouts", name: "Sprouts" },
  { id: "Dairy", name: "Dairy" }
];

async function main() {
  console.log("Starting seeding...");
  
  // Seed categories
  for (const cat of categories) {
    await prisma.category.upsert({
      where: { id: cat.id },
      update: { name: cat.name },
      create: { id: cat.id, name: cat.name }
    });
  }
  console.log("Seeded categories.");

  // Seed products
  for (const p of products) {
    await prisma.product.upsert({
      where: { id: p.id },
      update: {
        nameEn: p.nameEn,
        nameGu: p.nameGu,
        categoryId: p.category,
        svgType: p.svgType,
        imageUrl: p.imageUrl || null,
        prices: p.prices,
      },
      create: {
        id: p.id,
        nameEn: p.nameEn,
        nameGu: p.nameGu,
        categoryId: p.category,
        svgType: p.svgType,
        imageUrl: p.imageUrl || null,
        prices: p.prices,
      },
    });
  }
  console.log("Seeded products.");
  console.log("Seeding complete!");
}

main()
  .catch((e) => {
    console.error("Error seeding data:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    pool.end();
  });
